baseurl = "http://nukomeet.github.io/sharelex/"
languageCode = "fr-fr"
title = "ShareLex"
canonifyurls = true
pluralizeListTitles = false
publishdir = "dist"

[params]
ForumURL = "http://forum.sharelex.org"
